// Purpose: Styling definition for the ProductDetailScreen.
import { StyleSheet } from 'react-native';
import {
  BACKGROUND,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  BORDER,
  CARD_BG,
  SUCCESS_BG,
  SUCCESS_TEXT,
  DANGER_BG,
  DANGER_TEXT,
  PRIMARY
} from '../../constants/colors';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: BACKGROUND,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 12,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BORDER,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: CARD_BG,
    shadowColor: TEXT_SECONDARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 4,
    elevation: 1,
  },
  chevron: {
    width: 10,
    height: 10,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    borderColor: TEXT_PRIMARY,
    transform: [{ rotate: '45deg' }],
    marginLeft: 4,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: TEXT_PRIMARY,
    marginLeft: 16,
    flex: 1,
  },
  editLink: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  editIconText: {
    fontSize: 16,
    fontWeight: '700',
    color: PRIMARY,
    marginRight: 4,
  },
  editLinkText: {
    fontSize: 16,
    fontWeight: '600',
    color: PRIMARY,
  },
  stockCard: {
    backgroundColor: CARD_BG,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 20,
    padding: 24,
    alignItems: 'center',
    marginBottom: 16,
    shadowColor: TEXT_SECONDARY,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 6,
    elevation: 1,
  },
  stockCardLabel: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    fontWeight: '500',
    marginBottom: 4,
  },
  stockCardNumber: {
    fontSize: 64,
    fontWeight: '700',
    color: SUCCESS_TEXT,
  },
  stockCardUnit: {
    fontSize: 15,
    color: TEXT_SECONDARY,
    fontWeight: '500',
    marginTop: 4,
    marginBottom: 12,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: SUCCESS_BG,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: SUCCESS_TEXT,
    marginRight: 6,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '700',
    color: SUCCESS_TEXT,
  },
  metricsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 16,
  },
  metricCard: {
    flex: 1,
    backgroundColor: CARD_BG,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: 'center',
    shadowColor: TEXT_SECONDARY,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.02,
    shadowRadius: 3,
    elevation: 1,
  },
  metricLabel: {
    fontSize: 11,
    color: TEXT_SECONDARY,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    marginBottom: 4,
  },
  metricValue: {
    fontSize: 14,
    fontWeight: '700',
    color: TEXT_PRIMARY,
    textAlign: 'center',
  },
  actionsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  actionButton: {
    flex: 1,
    height: 52,
    borderRadius: 12,
    borderWidth: 1.5,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  stockInButton: {
    borderColor: '#D4EAC4',
    backgroundColor: '#F3F9EE',
  },
  stockOutButton: {
    borderColor: '#FCDDDC',
    backgroundColor: '#FDF2F2',
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: '600',
  },
  stockInText: {
    color: SUCCESS_TEXT,
  },
  stockOutText: {
    color: DANGER_TEXT,
  },
  arrowIcon: {
    fontSize: 16,
    fontWeight: '700',
  },
  historyTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: TEXT_PRIMARY,
    marginBottom: 14,
  },
  historyList: {
    backgroundColor: CARD_BG,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: BORDER,
    paddingHorizontal: 16,
  },
  historyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
  },
  historyDivider: {
    height: 1,
    backgroundColor: BORDER,
  },
  historyLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  historyIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  historyIconIn: {
    backgroundColor: SUCCESS_BG,
  },
  historyIconOut: {
    backgroundColor: DANGER_BG,
  },
  historyIconText: {
    fontSize: 16,
    fontWeight: '700',
  },
  historyInfo: {
    flex: 1,
  },
  historyType: {
    fontSize: 14,
    fontWeight: '600',
    color: TEXT_PRIMARY,
  },
  historyNote: {
    fontSize: 12,
    color: TEXT_SECONDARY,
    marginTop: 2,
  },
  historyRight: {
    alignItems: 'flex-end',
  },
  historyQuantity: {
    fontSize: 16,
    fontWeight: '700',
  },
  historyQuantityIn: {
    color: SUCCESS_TEXT,
  },
  historyQuantityOut: {
    color: DANGER_TEXT,
  },
  historyTime: {
    fontSize: 11,
    color: TEXT_SECONDARY,
    marginTop: 2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: CARD_BG,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 60,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 8,
  },
  modalHeader: {
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: TEXT_PRIMARY,
  },
  modalSubtitle: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    marginTop: 2,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  cancelButton: {
    flex: 1,
    height: 54,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BORDER,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: CARD_BG,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: TEXT_SECONDARY,
  },
  submitButtonWrapper: {
    flex: 1,
    paddingBottom: 34
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8F7FF',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 14,
    color: '#6B6B8A',
  },
  errorText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#A32D2D',
  },
  errorSub: {
    fontSize: 12,
    color: '#6B6B8A',
    marginTop: 6,
    textAlign: 'center',
    paddingHorizontal: 32,
  },
  emptyHistory: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    textAlign: 'center',
    paddingVertical: 24,
  },
});
